const data1 = [
  {
    _id: "63a48ea8d5c7d96ffab14827",
    index: 0,
    guid: "1cf8de00-0aae-4f1f-a913-b13054e021cd",
    isActive: true,
    balance: "$1,127.75",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "green",
    name: "Kendra Mcdowell",
    gender: "female",
    company: "KONGENE",
    email: "kendramcdowell@kongene.com",
    phone: "+1 (946) 521-2335",
    address: "625 Brooklyn Avenue, Marysville, North Carolina, 2254",
    about:
      "Voluptate do amet amet officia. Do proident duis adipisicing cillum velit eu officia aliquip sunt voluptate dolore. Est non esse in aliquip eiusmod eiusmod anim cillum adipisicing officia aliquip exercitation laboris proident.\r\n",
    registered: "2018-10-17T01:57:48 -06:-30",
    latitude: 59.518313,
    longitude: 125.083779,
    tags: ["laborum", "cupidatat", "nulla", "velit", "esse", "velit", "velit"],
    friends: [
      {
        id: 0,
        name: "Millie Young",
      },
      {
        id: 1,
        name: "Ronda Meyers",
      },
      {
        id: 2,
        name: "Natasha Leach",
      },
    ],
    greeting: "Hello, Kendra Mcdowell! You have 8 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "63a48ea809536f4c3972bd9d",
    index: 1,
    guid: "7295db44-ab1c-4fa9-960a-01ddc5891e01",
    isActive: false,
    balance: "$2,989.08",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "blue",
    name: "Minnie Potts",
    gender: "female",
    company: "FANFARE",
    email: "minniepotts@fanfare.com",
    phone: "+1 (934) 451-3009",
    address: "780 Baughman Place, Gouglersville, Minnesota, 3436",
    about:
      "Enim ex eiusmod adipisicing tempor. Excepteur amet aliquip incididunt ipsum consequat amet est occaecat in fugiat consectetur eiusmod anim occaecat. Sit exercitation labore magna aliquip deserunt incididunt sint voluptate sunt sunt.\r\n",
    registered: "2020-05-03T04:34:13 -06:-30",
    latitude: -19.962687,
    longitude: -99.110363,
    tags: ["velit", "ex", "est", "incididunt", "aliquip", "mollit", "tempor"],
    friends: [
      {
        id: 0,
        name: "Black Sparks",
      },
      {
        id: 1,
        name: "Chambers Forbes",
      },
      {
        id: 2,
        name: "Malone Vazquez",
      },
    ],
    greeting: "Hello, Minnie Potts! You have 6 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "63a48ea8c879ca9cf313a6c7",
    index: 2,
    guid: "8d5669ec-4ab6-441c-85ae-957adbe51c0b",
    isActive: true,
    balance: "$3,388.73",
    picture: "http://placehold.it/32x32",
    age: 38,
    eyeColor: "brown",
    name: "Cameron Schwartz",
    gender: "male",
    company: "QNEKT",
    email: "cameronschwartz@qnekt.com",
    phone: "+1 (960) 545-3273",
    address: "877 Ross Street, Kennedyville, Mississippi, 1625",
    about:
      "Eu ipsum enim irure dolore non nulla nisi occaecat aliquip reprehenderit. Magna anim tempor laborum labore quis ipsum adipisicing eu proident elit fugiat fugiat enim minim. Anim ipsum quis dolore velit laborum laborum ipsum magna.\r\n",
    registered: "2022-06-23T04:03:38 -06:-30",
    latitude: 17.097956,
    longitude: -75.646346,
    tags: [
      "veniam",
      "deserunt",
      "voluptate",
      "sunt",
      "id",
      "adipisicing",
      "non",
    ],
    friends: [
      {
        id: 0,
        name: "Blackwell Snider",
      },
      {
        id: 1,
        name: "Molly Doyle",
      },
      {
        id: 2,
        name: "Ruby Velasquez",
      },
    ],
    greeting: "Hello, Cameron Schwartz! You have 7 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "63a48ea8b89a6376e57a7226",
    index: 3,
    guid: "cbe01afb-5640-4f6a-b0dd-919f33f69a5e",
    isActive: true,
    balance: "$3,757.49",
    picture: "http://placehold.it/32x32",
    age: 22,
    eyeColor: "green",
    name: "Kenya Bradley",
    gender: "female",
    company: "QIMONK",
    email: "kenyabradley@qimonk.com",
    phone: "+1 (983) 467-2144",
    address: "944 Eaton Court, Eastmont, New Mexico, 2854",
    about:
      "Irure deserunt mollit ut pariatur. Reprehenderit id ex est aliqua nostrud ipsum. Reprehenderit tempor aliquip ipsum deserunt Lorem ad occaecat. Exercitation dolore consectetur minim adipisicing in ad minim enim dolor quis aliqua.\r\n",
    registered: "2016-08-12T02:20:16 -06:-30",
    latitude: 65.588231,
    longitude: -178.878709,
    tags: [
      "aliqua",
      "ad",
      "laborum",
      "voluptate",
      "velit",
      "consequat",
      "esse",
    ],
    friends: [
      {
        id: 0,
        name: "Sharp Mercado",
      },
      {
        id: 1,
        name: "Tate Mayer",
      },
      {
        id: 2,
        name: "Carmella Heath",
      },
    ],
    greeting: "Hello, Kenya Bradley! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "63a48ea8471582c24df206a4",
    index: 4,
    guid: "47477121-91ae-4358-9479-b14090a7c143",
    isActive: false,
    balance: "$2,687.48",
    picture: "http://placehold.it/32x32",
    age: 31,
    eyeColor: "green",
    name: "Marina Hooper",
    gender: "female",
    company: "COSMOSIS",
    email: "marinahooper@cosmosis.com",
    phone: "+1 (981) 540-2338",
    address: "868 Williams Place, Buxton, Arkansas, 1379",
    about:
      "Sint culpa ut minim Lorem velit. Nisi consequat fugiat excepteur veniam. Voluptate consequat Lorem exercitation labore fugiat voluptate ipsum ut nisi sint irure ex dolore. Amet dolore ex officia mollit enim elit.\r\n",
    registered: "2018-01-14T02:45:37 -06:-30",
    latitude: 44.955889,
    longitude: -72.434898,
    tags: [
      "officia",
      "aliqua",
      "cupidatat",
      "in",
      "amet",
      "consequat",
      "minim",
    ],
    friends: [
      {
        id: 0,
        name: "Sara Cooley",
      },
      {
        id: 1,
        name: "Dawson Conway",
      },
      {
        id: 2,
        name: "Pittman Boyle",
      },
    ],
    greeting: "Hello, Marina Hooper! You have 10 unread messages.",
    favoriteFruit: "banana",
  },
];

const data2 = [
  {
    _id: "63a48ef2e12ba4fcc0d0a87b",
    index: 0,
    guid: "1a73b4b6-f5a9-48fc-a8be-bc30aa6cd237",
    isActive: false,
    balance: "$3,268.87",
    picture: "http://placehold.it/32x32",
    age: 24,
    eyeColor: "blue",
    name: "Krystal Nieves",
    gender: "female",
    company: "ACUSAGE",
    email: "krystalnieves@acusage.com",
    phone: "+1 (943) 429-2807",
    address: "612 Poplar Avenue, Alleghenyville, Connecticut, 6313",
    about:
      "Cupidatat id quis excepteur elit sunt officia ea tempor et dolor deserunt ex deserunt amet. In excepteur culpa ipsum ad. Est quis officia adipisicing reprehenderit esse excepteur quis cillum. Officia eiusmod aliqua voluptate cillum dolore proident Lorem proident officia eu reprehenderit veniam veniam. Veniam reprehenderit exercitation mollit eiusmod officia in in. Ex ullamco ex occaecat exercitation eiusmod ut ex.\r\n",
    registered: "2019-11-03T03:28:29 -06:-30",
    latitude: -59.460022,
    longitude: -94.408136,
    tags: ["sunt", "mollit", "ipsum", "aliquip", "commodo", "incididunt", "id"],
    friends: [
      {
        id: 0,
        name: "Leblanc Carroll",
      },
      {
        id: 1,
        name: "Victoria Erickson",
      },
      {
        id: 2,
        name: "Pitts Carney",
      },
    ],
    greeting: "Hello, Krystal Nieves! You have 1 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "63a48ef2288d182b5fef00b1",
    index: 1,
    guid: "7137b95b-34e0-4a3e-8deb-f8989dfb20ea",
    isActive: false,
    balance: "$2,023.41",
    picture: "http://placehold.it/32x32",
    age: 26,
    eyeColor: "blue",
    name: "Cherie Le",
    gender: "female",
    company: "PHOLIO",
    email: "cheriele@pholio.com",
    phone: "+1 (956) 444-3959",
    address: "777 Union Avenue, Duryea, Arkansas, 571",
    about:
      "Consectetur pariatur laborum ex culpa laborum ipsum magna. Fugiat occaecat sint officia do nisi esse ad. Reprehenderit voluptate elit anim exercitation consectetur quis velit id adipisicing. Esse excepteur dolore nulla deserunt consectetur et ut. Occaecat nostrud sit officia quis non eu. Officia mollit qui do amet in veniam ad adipisicing labore velit laboris cupidatat. Eu sunt sit esse laborum dolor nulla aliqua aliquip proident aute fugiat ipsum commodo.\r\n",
    registered: "2018-01-01T01:35:11 -06:-30",
    latitude: -41.767446,
    longitude: -39.307616,
    tags: [
      "cupidatat",
      "in",
      "adipisicing",
      "aliqua",
      "consequat",
      "adipisicing",
      "ut",
    ],
    friends: [
      {
        id: 0,
        name: "Mercado Monroe",
      },
      {
        id: 1,
        name: "Joan Sheppard",
      },
      {
        id: 2,
        name: "Sharpe Rodriquez",
      },
    ],
    greeting: "Hello, Cherie Le! You have 8 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "63a48ef2456d663580d46f68",
    index: 2,
    guid: "4f802983-d870-4feb-823a-f9890a926d69",
    isActive: true,
    balance: "$1,784.49",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "green",
    name: "Marion Wolfe",
    gender: "female",
    company: "ACIUM",
    email: "marionwolfe@acium.com",
    phone: "+1 (993) 474-2741",
    address: "958 Nevins Street, Manchester, Virginia, 732",
    about:
      "Voluptate ut amet nisi aute sunt fugiat veniam et qui qui. Pariatur cupidatat dolor dolore cillum fugiat ipsum sunt. Occaecat dolor deserunt deserunt tempor minim enim in aliquip proident magna anim sit nulla.\r\n",
    registered: "2018-12-22T10:19:33 -06:-30",
    latitude: -89.434197,
    longitude: 26.572215,
    tags: [
      "adipisicing",
      "tempor",
      "aliquip",
      "labore",
      "irure",
      "consectetur",
      "sit",
    ],
    friends: [
      {
        id: 0,
        name: "Hunt David",
      },
      {
        id: 1,
        name: "Bernice Kramer",
      },
      {
        id: 2,
        name: "Miranda Wiggins",
      },
    ],
    greeting: "Hello, Marion Wolfe! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
];

module.exports = { data1, data2 };
